### ISSUE TITLE
Maintain dipole branch

### ISSUE THREAD

**Issue by davkovacs** [ACEsuit/ACEatoms.jl#5]
I have started doing some initial development on the dipole branch, but @cortner there were some changes and a version bump on the main branch in the mean time. This results in the dipole branch not working any more. What should we do? Could we merge main into the dipole branch?

**Comment by cortner** [comment]
so now that everything else has been updated, I'll also get the dipole stuff up and running again asap. And then we can see what we need to do to fix your dipole branch

**Comment by cortner** [comment]
@davkovacs Can we close this?

**Comment by davkovacs** [comment]
yes, I will make sure to merge main into dipole-2 regularly.
